[package]
name = "generator"
version = "0.1.0"
authors = ["Ryan1729 <Ryan1729@gmail.com>"]

[dependencies]
rand = "0.5"
project_common = { path = "../project_common" }

[dev-dependencies]
quickcheck = "0.6.2"
